# docker-compose.yml
version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "3001:3000"
  database:
    image: mongo:4.4
    ports:
      - "27017:27017"